/** Common airlines for datalist / quick pick (free text still allowed). */
export const AIRLINE_SUGGESTIONS: readonly string[] = [
  "Aer Lingus",
  "Aeroméxico",
  "Air Canada",
  "Air France",
  "Air New Zealand",
  "Alaska Airlines",
  "Allegiant Air",
  "American Airlines",
  "ANA (All Nippon Airways)",
  "British Airways",
  "Cathay Pacific",
  "Delta Air Lines",
  "Emirates",
  "Etihad Airways",
  "Frontier Airlines",
  "Hawaiian Airlines",
  "Iberia",
  "ITA Airways",
  "Japan Airlines (JAL)",
  "JetBlue Airways",
  "KLM Royal Dutch Airlines",
  "Korean Air",
  "LATAM Airlines",
  "Lufthansa",
  "Norwegian",
  "Qantas",
  "Qatar Airways",
  "Ryanair",
  "Singapore Airlines",
  "Southwest Airlines",
  "Spirit Airlines",
  "Sun Country Airlines",
  "Swiss International Air Lines",
  "TAP Air Portugal",
  "Turkish Airlines",
  "United Airlines",
  "Virgin Atlantic",
  "WestJet",
];
