/** Major airports for combobox search (IATA + display). */
export type Airport = { code: string; name: string; city: string };

export const AIRPORTS: readonly Airport[] = [
  { code: "ATL", name: "Hartsfield–Jackson Atlanta International", city: "Atlanta" },
  { code: "LAX", name: "Los Angeles International", city: "Los Angeles" },
  { code: "ORD", name: "O'Hare International", city: "Chicago" },
  { code: "DFW", name: "Dallas/Fort Worth International", city: "Dallas–Fort Worth" },
  { code: "DEN", name: "Denver International", city: "Denver" },
  { code: "JFK", name: "John F. Kennedy International", city: "New York" },
  { code: "SFO", name: "San Francisco International", city: "San Francisco" },
  { code: "SEA", name: "Seattle–Tacoma International", city: "Seattle" },
  { code: "LAS", name: "Harry Reid International", city: "Las Vegas" },
  { code: "MCO", name: "Orlando International", city: "Orlando" },
  { code: "EWR", name: "Newark Liberty International", city: "Newark" },
  { code: "MIA", name: "Miami International", city: "Miami" },
  { code: "PHX", name: "Phoenix Sky Harbor International", city: "Phoenix" },
  { code: "IAH", name: "George Bush Intercontinental", city: "Houston" },
  { code: "BOS", name: "Logan International", city: "Boston" },
  { code: "MSP", name: "Minneapolis–Saint Paul International", city: "Minneapolis" },
  { code: "DTW", name: "Detroit Metropolitan", city: "Detroit" },
  { code: "PHL", name: "Philadelphia International", city: "Philadelphia" },
  { code: "LGA", name: "LaGuardia", city: "New York" },
  { code: "BWI", name: "Baltimore/Washington International", city: "Baltimore" },
  { code: "SLC", name: "Salt Lake City International", city: "Salt Lake City" },
  { code: "DCA", name: "Ronald Reagan Washington National", city: "Washington, D.C." },
  { code: "IAD", name: "Washington Dulles International", city: "Washington, D.C." },
  { code: "SAN", name: "San Diego International", city: "San Diego" },
  { code: "TPA", name: "Tampa International", city: "Tampa" },
  { code: "PDX", name: "Portland International", city: "Portland, OR" },
  { code: "STL", name: "St. Louis Lambert International", city: "St. Louis" },
  { code: "BNA", name: "Nashville International", city: "Nashville" },
  { code: "AUS", name: "Austin–Bergstrom International", city: "Austin" },
  { code: "SJC", name: "Norman Y. Mineta San José International", city: "San Jose" },
  { code: "SMF", name: "Sacramento International", city: "Sacramento" },
  { code: "MSY", name: "Louis Armstrong New Orleans International", city: "New Orleans" },
  { code: "RDU", name: "Raleigh–Durham International", city: "Raleigh" },
  { code: "PIT", name: "Pittsburgh International", city: "Pittsburgh" },
  { code: "CLE", name: "Cleveland Hopkins International", city: "Cleveland" },
  { code: "IND", name: "Indianapolis International", city: "Indianapolis" },
  { code: "HNL", name: "Daniel K. Inouye International", city: "Honolulu" },
  { code: "ANC", name: "Ted Stevens Anchorage International", city: "Anchorage" },
  { code: "YYZ", name: "Toronto Pearson International", city: "Toronto" },
  { code: "YVR", name: "Vancouver International", city: "Vancouver" },
  { code: "YUL", name: "Montréal–Trudeau International", city: "Montréal" },
  { code: "LHR", name: "Heathrow", city: "London" },
  { code: "LGW", name: "Gatwick", city: "London" },
  { code: "STN", name: "Stansted", city: "London" },
  { code: "CDG", name: "Charles de Gaulle", city: "Paris" },
  { code: "ORY", name: "Orly", city: "Paris" },
  { code: "AMS", name: "Schiphol", city: "Amsterdam" },
  { code: "FRA", name: "Frankfurt Airport", city: "Frankfurt" },
  { code: "MUC", name: "Munich Airport", city: "Munich" },
  { code: "ZRH", name: "Zurich Airport", city: "Zurich" },
  { code: "VIE", name: "Vienna International", city: "Vienna" },
  { code: "FCO", name: "Leonardo da Vinci–Fiumicino", city: "Rome" },
  { code: "MXP", name: "Malpensa", city: "Milan" },
  { code: "MAD", name: "Adolfo Suárez Madrid–Barajas", city: "Madrid" },
  { code: "BCN", name: "Barcelona–El Prat", city: "Barcelona" },
  { code: "LIS", name: "Humberto Delgado", city: "Lisbon" },
  { code: "DUB", name: "Dublin Airport", city: "Dublin" },
  { code: "ARN", name: "Stockholm Arlanda", city: "Stockholm" },
  { code: "CPH", name: "Copenhagen Airport", city: "Copenhagen" },
  { code: "OSL", name: "Oslo Gardermoen", city: "Oslo" },
  { code: "HEL", name: "Helsinki Airport", city: "Helsinki" },
  { code: "IST", name: "Istanbul Airport", city: "Istanbul" },
  { code: "DXB", name: "Dubai International", city: "Dubai" },
  { code: "DOH", name: "Hamad International", city: "Doha" },
  { code: "AUH", name: "Zayed International", city: "Abu Dhabi" },
  { code: "TLV", name: "Ben Gurion", city: "Tel Aviv" },
  { code: "NRT", name: "Narita International", city: "Tokyo" },
  { code: "HND", name: "Haneda Airport", city: "Tokyo" },
  { code: "KIX", name: "Kansai International", city: "Osaka" },
  { code: "ICN", name: "Incheon International", city: "Seoul" },
  { code: "PEK", name: "Beijing Capital International", city: "Beijing" },
  { code: "PKX", name: "Beijing Daxing International", city: "Beijing" },
  { code: "PVG", name: "Shanghai Pudong International", city: "Shanghai" },
  { code: "HKG", name: "Hong Kong International", city: "Hong Kong" },
  { code: "TPE", name: "Taoyuan International", city: "Taipei" },
  { code: "SIN", name: "Changi Airport", city: "Singapore" },
  { code: "BKK", name: "Suvarnabhumi", city: "Bangkok" },
  { code: "KUL", name: "Kuala Lumpur International", city: "Kuala Lumpur" },
  { code: "DEL", name: "Indira Gandhi International", city: "New Delhi" },
  { code: "BOM", name: "Chhatrapati Shivaji Maharaj International", city: "Mumbai" },
  { code: "SYD", name: "Sydney Kingsford Smith", city: "Sydney" },
  { code: "MEL", name: "Melbourne Airport", city: "Melbourne" },
  { code: "BNE", name: "Brisbane Airport", city: "Brisbane" },
  { code: "AKL", name: "Auckland Airport", city: "Auckland" },
  { code: "WLG", name: "Wellington International", city: "Wellington" },
  { code: "JNB", name: "O. R. Tambo International", city: "Johannesburg" },
  { code: "CPT", name: "Cape Town International", city: "Cape Town" },
  { code: "GRU", name: "São Paulo/Guarulhos", city: "São Paulo" },
  { code: "GIG", name: "Rio de Janeiro/Galeão", city: "Rio de Janeiro" },
  { code: "MEX", name: "Mexico City International", city: "Mexico City" },
  { code: "CUN", name: "Cancún International", city: "Cancún" },
  { code: "SJU", name: "Luis Muñoz Marín International", city: "San Juan" },
  { code: "NAS", name: "Lynden Pindling International", city: "Nassau" },
];

export function filterAirports(query: string, limit = 12): Airport[] {
  const q = query.trim().toLowerCase();
  if (!q) return [...AIRPORTS].slice(0, limit);
  const scored: { a: Airport; s: number }[] = [];
  for (const a of AIRPORTS) {
    const code = a.code.toLowerCase();
    const city = a.city.toLowerCase();
    const name = a.name.toLowerCase();
    if (code.startsWith(q)) scored.push({ a, s: 0 });
    else if (city.includes(q) || name.includes(q) || code.includes(q)) scored.push({ a, s: 1 });
  }
  scored.sort((x, y) => x.s - y.s);
  return scored.slice(0, limit).map((x) => x.a);
}
