import type { CuratedAttraction, CuratedCity, CuratedExperience } from "@/lib/curated-types";
import type { StoryKind } from "@/components/itinerary/storybook/types";

/** HD Unsplash URLs — keep query params for stable caching */
const u = (id: string) =>
  `https://images.unsplash.com/${id}?w=1920&q=88&auto=format&fit=crop`;

function ex(
  citySlug: string,
  key: string,
  title: string,
  subtitle: string,
  image: string,
  locationLabel: string,
  storyKind: StoryKind,
): CuratedExperience {
  return {
    id: `${citySlug}/${key}`,
    experienceKey: key,
    title,
    subtitle,
    image,
    locationLabel,
    storyKind,
  };
}

/** Used when the database is empty or unreachable (same content as seed). */
export const FALLBACK_CITIES: CuratedCity[] = [
  {
    slug: "paris",
    name: "Paris",
    country: "France",
    tagline: "Museums, cafés, and riverside walks",
    heroImage: u("photo-1502602898657-3e91760cbb34"),
    experiences: [
      ex(
        "paris",
        "louvre",
        "Louvre & Tuileries morning",
        "Classics first, then garden stroll — beat the midday crowds.",
        u("photo-1565099824688-e93eb20fe622"),
        "Louvre Museum, Paris",
        "activity",
      ),
      ex(
        "paris",
        "seine",
        "Sunset along the Seine",
        "Bridge hopping from Île Saint-Louis to the Eiffel sparkles.",
        u("photo-1431278762619-41212f08b121"),
        "Seine riverfront, Paris",
        "activity",
      ),
      ex(
        "paris",
        "bistro",
        "Left Bank bistro night",
        "Reserve a zinc bar table for steak frites and natural wine.",
        u("photo-1550966871-3ed3cdb5ed0c"),
        "Saint-Germain, Paris",
        "meal",
      ),
      ex(
        "paris",
        "stay-marais",
        "Boutique stay in the Marais",
        "Walkable to galleries, falafel rows, and vintage shops.",
        u("photo-1520250497591-112f2f40a3f4"),
        "Le Marais, Paris",
        "stay",
      ),
    ],
  },
  {
    slug: "tokyo",
    name: "Tokyo",
    country: "Japan",
    tagline: "Neon nights and quiet shrines",
    heroImage: u("photo-1540959733332-eab4deabeeaf"),
    experiences: [
      ex(
        "tokyo",
        "shibuya",
        "Shibuya crossing & towers",
        "Golden hour views, then basement food halls.",
        u("photo-1542051841857-5f90071e7989"),
        "Shibuya, Tokyo",
        "activity",
      ),
      ex(
        "tokyo",
        "tsukiji-outer",
        "Tsukiji outer market breakfast",
        "Grilled seafood, tamago, and strong morning coffee.",
        u("photo-1580822182913-b40260d6b0b1"),
        "Tsukiji, Tokyo",
        "meal",
      ),
      ex(
        "tokyo",
        "meiji",
        "Meiji Shrine forest walk",
        "Cedar paths and quiet contrast to the city pulse.",
        u("photo-1528360983277-13d401cdc186"),
        "Meiji Jingu, Tokyo",
        "activity",
      ),
      ex(
        "tokyo",
        "shinjuku-stay",
        "Shinjuku base camp",
        "Trains in every direction — perfect for day trips.",
        u("photo-1493809842364-78817add7ffb"),
        "Shinjuku, Tokyo",
        "stay",
      ),
    ],
  },
  {
    slug: "new-york",
    name: "New York",
    country: "USA",
    tagline: "Skyline energy and neighborhood gems",
    heroImage: u("photo-1496442226666-8d4d0ac62e5e"),
    experiences: [
      ex(
        "new-york",
        "central-park",
        "Central Park loop",
        "Bethesda Terrace, rowboats, and a museum on the edge.",
        u("photo-1568515387631-8b650bbcdb90"),
        "Central Park, NYC",
        "activity",
      ),
      ex(
        "new-york",
        "brooklyn-bridge",
        "Brooklyn Bridge at blue hour",
        "Walk Manhattan → DUMBO for pizza with a view.",
        u("photo-1514565131-fce0801e5785"),
        "Brooklyn Bridge, NYC",
        "activity",
      ),
      ex(
        "new-york",
        "soho-dinner",
        "Soho tasting menu",
        "Book early — chef’s counter slots disappear fast.",
        u("photo-1414235077428-338989a2e8c0"),
        "SoHo, NYC",
        "meal",
      ),
      ex(
        "new-york",
        "midtown-hotel",
        "Midtown stay near the parks",
        "Short walks to MoMA, Broadway, and Hudson Yards.",
        u("photo-1566073771259-6a8506099945"),
        "Midtown, NYC",
        "stay",
      ),
    ],
  },
  {
    slug: "barcelona",
    name: "Barcelona",
    country: "Spain",
    tagline: "Gaudí, tapas, and Mediterranean light",
    heroImage: u("photo-1583422409516-2895a77efded"),
    experiences: [
      ex(
        "barcelona",
        "sagrada",
        "Sagrada Família timed entry",
        "Morning light through the stained glass is unforgettable.",
        u("photo-1562883676-8c7feb83f09b"),
        "Sagrada Família, Barcelona",
        "activity",
      ),
      ex(
        "barcelona",
        "gothic-quarter",
        "Gothic Quarter tapas crawl",
        "Pinchos, vermouth, and hidden plazas after dark.",
        u("photo-1551218808-94e220e084d2"),
        "Barri Gòtic, Barcelona",
        "meal",
      ),
      ex(
        "barcelona",
        "park-guell",
        "Park Güell viewpoints",
        "Mosaic terraces overlooking the city grid.",
        u("photo-1562883676-8c7feb83f09b"),
        "Park Güell, Barcelona",
        "activity",
      ),
      ex(
        "barcelona",
        "beach-stay",
        "Stay near Barceloneta",
        "Morning swims before city sightseeing.",
        u("photo-1559827260-dc66d52bef19"),
        "Barceloneta, Barcelona",
        "stay",
      ),
    ],
  },
  {
    slug: "lisbon",
    name: "Lisbon",
    country: "Portugal",
    tagline: "Trams, tiles, and Atlantic breezes",
    heroImage: u("photo-1585208798174-6cedd86e019a"),
    experiences: [
      ex(
        "lisbon",
        "alfama",
        "Alfama sunrise miradouros",
        "Winding alleys, azulejos, and fado at night.",
        u("photo-1555881400-74d7acaacd8b"),
        "Alfama, Lisbon",
        "activity",
      ),
      ex(
        "lisbon",
        "pasteis",
        "Pastéis and riverfront",
        "Belém classics, then a walk along the Tagus.",
        u("photo-1585208798174-6cedd86e019a"),
        "Belém, Lisbon",
        "meal",
      ),
      ex(
        "lisbon",
        "sintra-day",
        "Sintra day trip",
        "Palaces in the mist — leave early for fewer buses.",
        u("photo-1506905925346-21bda4d32df4"),
        "Sintra (from Lisbon)",
        "activity",
      ),
      ex(
        "lisbon",
        "baixa-stay",
        "Baixa pied-à-terre",
        "Flat walks to Rossio, Chiado, and the river.",
        u("photo-1566073771259-6a8506099945"),
        "Baixa, Lisbon",
        "stay",
      ),
    ],
  },
  {
    slug: "kyoto",
    name: "Kyoto",
    country: "Japan",
    tagline: "Temples, bamboo, and kaiseki",
    heroImage: u("photo-1493976040374-85c8e12d0d0e"),
    experiences: [
      ex(
        "kyoto",
        "fushimi",
        "Fushimi Inari at dawn",
        "Torii tunnels before tour groups arrive.",
        u("photo-1478436127897-769e1b3f0f36"),
        "Fushimi Inari, Kyoto",
        "activity",
      ),
      ex(
        "kyoto",
        "arashiyama",
        "Arashiyama bamboo grove",
        "River boats optional — monkey park nearby.",
        u("photo-1528360983277-13d401cdc186"),
        "Arashiyama, Kyoto",
        "activity",
      ),
      ex(
        "kyoto",
        "kaiseki",
        "Kaiseki in a ryokan",
        "Seasonal courses — book weeks ahead in peak season.",
        u("photo-1580822182913-b40260d6b0b1"),
        "Higashiyama, Kyoto",
        "meal",
      ),
      ex(
        "kyoto",
        "gion-stay",
        "Gion neighborhood stay",
        "Evening strolls past machiya and lantern-lit lanes.",
        u("photo-1520250497591-112f2f40a3f4"),
        "Gion, Kyoto",
        "stay",
      ),
    ],
  },
];

export const FALLBACK_TOP_ATTRACTIONS: CuratedAttraction[] = [
  {
    id: "eiffel",
    title: "Eiffel Tower",
    city: "Paris",
    citySlug: "paris",
    image: u("photo-1511739001486-6bfe10ce785f"),
  },
  {
    id: "liberty",
    title: "Statue of Liberty",
    city: "New York",
    citySlug: "new-york",
    image: u("photo-1568515387631-8b650bbcdb90"),
  },
  {
    id: "shibuya-scramble",
    title: "Shibuya Crossing",
    city: "Tokyo",
    citySlug: "tokyo",
    image: u("photo-1542051841857-5f90071e7989"),
  },
  {
    id: "sagrada-facade",
    title: "Sagrada Família",
    city: "Barcelona",
    citySlug: "barcelona",
    image: u("photo-1583422409516-2895a77efded"),
  },
  {
    id: "tram-28",
    title: "Historic tram 28",
    city: "Lisbon",
    citySlug: "lisbon",
    image: u("photo-1555881400-74d7acaacd8b"),
  },
  {
    id: "kinkakuji",
    title: "Kinkaku-ji",
    city: "Kyoto",
    citySlug: "kyoto",
    image: u("photo-1545569341-9eb8b30979d9"),
  },
];
